version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - php
    networks:
      - lnmp_network

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/logs:/var/log/php-fpm  # 挂载日志目录
    command: >
      bash -c "apt-get update && apt-get install -y \
      && docker-php-ext-install mysqli \
      && docker-php-ext-enable mysqli \
      && php-fpm"
    networks:
      - lnmp_network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "33060:3306"
    networks:
      - lnmp_network

networks:
  lnmp_network:
    driver: bridge

volumes:
  mysql_data:
